# Default values for my-flask-app
# This is a YAML-formatted file.

# Application settings
app:
  name: flask-app
  port: 5000

# Deployment configuration
deployment:
  name: flask-deployment
  replicas: 2
  annotations: {}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
image:
  repository:
  tag: 

# Service configuration
service:
  name: flask-service
  type: NodePort
  port: 5000
  targetPort: 5000
  protocol: TCP

# Ingress configuration
ingress:
  enabled: true
  name: flask-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "instance"
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.alpha.kubernetes.io/hostname: "wwww.saharbittman.com"
    alb.ingress.kubernetes.io/target-group-port: "80"
  hosts:
    - host: "wwww.saharbittman.com"
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true
    secretName: ""
    hosts:
      - "*.saharbittman.com"